import { course_item } from "../models/course-item";

export const MOCK_COURSES: course_item[] = [
    {
      id: 1,
      img_url: "https://img.youtube.com/vi/tVzUXW6siu0/hqdefault.jpg",
      batch_nO: 3,
      no_of_seat: 10,
      rem_days: 5,
      course_id: "WD101",
      course_name: "Web Development From Scratch",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 139,
      category: "Web Development",
      isPremium: true,
      course_fee: 1500,
      isEnrolled: false,
      playlistId: 'PLu0W_9lII9agq5TrH9XLIKQvv0iaF2X3w',

    },
    {
      id: 2,
      img_url: "https://img.youtube.com/vi/RWXKysImabs/hqdefault.jpg",
      batch_nO: 2,
      no_of_seat: 2,
      rem_days: 2,
      course_id: "WD102",
      course_name: "Learn Dot Net Development",
      course_desc: "This project showcases web application development using the .NET framework, focusing on building scalable backend services with ASP.NET Core. It includes implementation of RESTful APIs, integration with a SQL Server database, and application of MVC architecture for clean and maintainable code structure.",
      no_of_class: 10,
      category: "Web Development",
      isPremium: false,
      course_fee: 0,
      isEnrolled: false,
      playlistId: 'RWXKysImabs',

    },
    {
      id: 3,
      img_url: "https://img.youtube.com/vi/EsUL2bfKKLc/hqdefault.jpg",
      batch_nO: 13,
      no_of_seat: 2,
      rem_days: 7,
      course_id: "WD103",
      course_name: "Full Stack Web Development (MERN)",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 30,
      category: "Web Development",
      isPremium: true,
      course_fee: 2500,
      isEnrolled: false,
      playlistId: 'EsUL2bfKKLc',

    },
    {
      id: 4,
      img_url: "https://img.youtube.com/vi/5NgNicANyqM/hqdefault.jpg",
      batch_nO: 4,
      no_of_seat: 20,
      rem_days: 15,
      course_id: "AI101",
      course_name: "Learn Artificial Intelligence",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 20,
      category: "Artificial Intelligence",
      isPremium: false,
      course_fee: 0,
      isEnrolled: false,
      playlistId: '5NgNicANyqM',

    },
    {
      id: 5,
      img_url: "https://img.youtube.com/vi/7WRlYJFG7YI/hqdefault.jpg",
      batch_nO: 3,
      no_of_seat: 22,
      rem_days: 2,
      course_id: "DE101",
      course_name: "Data Science Full Course",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 14,
      category: "Data Engineering",
      isPremium: false,
      course_fee: 0,
      isEnrolled: false,
      playlistId: '7WRlYJFG7YI',

    },
    {
      id: 6,
      img_url: "https://img.youtube.com/vi/fNzpcB7ODxQ/hqdefault.jpg",
      batch_nO: 11,
      no_of_seat: 4,
      rem_days: 8,
      course_id: "CSEC101",
      course_name: "Learn Ethical Hacking",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 80,
      category: "Cyber Security",
      isPremium: true,
      course_fee: 3000,
      isEnrolled: false,
      playlistId: 'fNzpcB7ODxQ',

    },
    {
      id: 7,
      img_url: "https://img.youtube.com/vi/-TkoO8Z07hI/hqdefault.jpg",
      batch_nO: 20,
      no_of_seat: 6,
      rem_days: 5,
      course_id: "PROG101",
      course_name: "Learn C++ Language",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 40,
      category: "Programming",
      isPremium: false,
      course_fee: 0,
      isEnrolled: false,
      playlistId: '-TkoO8Z07hI',

    },
    {
      id: 8,
      img_url: "https://img.youtube.com/vi/UrsmFxEIp5k/hqdefault.jpg",
      batch_nO: 9,
      no_of_seat: 4,
      rem_days: 2,
      course_id: "PROG102",
      course_name: "Python Ultimate Course",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 23,
      category: "Programming",
      isPremium: true,
      course_fee: 1200,
      isEnrolled: false,
      playlistId: 'UrsmFxEIp5k',

    },
    {
      id: 9,
      img_url: "https://img.youtube.com/vi/jpWj2kKcen4/hqdefault.jpg",
      batch_nO: 5,
      no_of_seat: 1,
      rem_days: 2,
      course_id: "DOPS101",
      course_name: "DevOps Full Course",
      course_desc: "This project demonstrates core DevOps practices, including continuous integration, continuous deployment (CI/CD), infrastructure automation, and containerization. Tools like Git, Jenkins/GitHub Actions, Docker, and Kubernetes are used to streamline development workflows and ensure reliable, scalable software delivery.",
      no_of_class: 55,
      category: "Web Development",
      isPremium: false,
      course_fee: 0,
      isEnrolled: false,
      playlistId: 'jpWj2kKcen4',

    },
    {
      id: 10,
      img_url: "https://img.youtube.com/vi/C1NgOmoOszc/hqdefault.jpg",
      batch_nO: 6,
      no_of_seat: 14,
      rem_days: 8,
      course_id: "WD104",
      course_name: "Django Full Course",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 60,
      category: "Web Development",
      isPremium: false,
      course_fee: 0,
      isEnrolled: true,
      playlistId: 'PLjVLYmrlmjGcyt3m6rt21nfjhYSWP_Ue_',

    },
    {
      id: 11,
      img_url: "https://img.youtube.com/vi/GwIo3gDZCVQ/hqdefault.jpg",
      batch_nO: 2,
      no_of_seat: 2,
      rem_days: 1,
      course_id: "AI102",
      course_name: "Machine Learning Full Course",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 77,
      category: "Artificial Intelligence",
      isPremium: true,
      course_fee: 5000,
      isEnrolled: false,
      playlistId: 'GwIo3gDZCVQ',

    },
    {
      id: 12,
      img_url: "https://img.youtube.com/vi/G1P2IaBcXx8/hqdefault.jpg",
      batch_nO: 5,
      no_of_seat: 2,
      rem_days: 25,
      course_id: "AI103",
      course_name: "Deep Learning Full Course",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 47,
      category: "Artificial Intelligence",
      isPremium: false,
      course_fee: 0,
      isEnrolled: false,
      playlistId: 'G1P2IaBcXx8',

    },
    {
      id: 13,
      img_url: "https://img.youtube.com/vi/ykrE849Yq68/hqdefault.jpg",
      batch_nO: 11,
      no_of_seat: 4,
      rem_days: 8,
      course_id: "CSEC102",
      course_name: "Learn Networking For Cyber Security",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 52,
      category: "Cyber Security",
      isPremium: false,
      course_fee: 0,
      isEnrolled: true,
      playlistId: 'ykrE849Yq68',

    },
    {
      id: 14,
      img_url: "https://img.youtube.com/vi/GoXwIVyNvX0/hqdefault.jpg",
      batch_nO: 19,
      no_of_seat: 4,
      rem_days: 22,
      course_id: "PROG103",
      course_name: "Learn Java Full Course",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 40,
      category: "Programming",
      isPremium: true,
      course_fee: 1800,
      isEnrolled: false,
      playlistId: 'GoXwIVyNvX0',

    },
    {
      id: 15,
      img_url: "https://img.youtube.com/vi/MXlZCgh2M6A/hqdefault.jpg",
      batch_nO: 10,
      no_of_seat: 8,
      rem_days: 21,
      course_id: "PROG104",
      course_name: "Ruby For Beginners",
      course_desc: "This project demonstrates full-stack web development using the MERN stack (MongoDB, Express.js, React.js, and Node.js). It covers building a responsive frontend with React, managing backend APIs with Express and Node, and integrating MongoDB for data storage—offering a complete end-to-end application development experience.",
      no_of_class: 60,
      category: "Programming",
      isPremium: false,
      course_fee: 0,
      isEnrolled: true,
      playlistId: 'MXlZCgh2M6A',

    }
]